Raise minimum tested version to rust 1.46
Required by assert_cmd's use of track_caller.

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
       --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:154:5
        |
    154 |     #[track_caller]
        |     ^^^^^^^^^^^^^^^

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
       --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:183:5
        |
    183 |     #[track_caller]
        |     ^^^^^^^^^^^^^^^

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
       --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:197:5
        |
    197 |     #[track_caller]
        |     ^^^^^^^^^^^^^^^

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
       --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:258:5
        |
    258 |     #[track_caller]
        |     ^^^^^^^^^^^^^^^

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
       --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:356:5
        |
    356 |     #[track_caller]
        |     ^^^^^^^^^^^^^^^

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
       --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:452:5
        |
    452 |     #[track_caller]
        |     ^^^^^^^^^^^^^^^

    error[E0658]: the `#[track_caller]` attribute is an experimental feature
        --> github.com-1ecc6299db9ec823/assert_cmd-2.0.2/src/assert.rs:1034:5
         |
    1034 |     #[track_caller]
         |     ^^^^^^^^^^^^^^^