Raise minimum tested toolchain to rust 1.60
Required by the predicates-tree crate, which is a dependency of our
dev-dependency on assert_cmd.

    error: failed to parse manifest at `github.com-1ecc6299db9ec823/predicates-tree-1.0.7/Cargo.toml`

    Caused by:
      feature `edition2021` is required

      The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.55.0 (32da73ab1 2021-08-23)).
      Consider trying a newer version of Cargo (this may require the nightly release).
      See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.

    error: package `predicates-tree v1.0.7` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.56.0