Raise minimum tested version to rustc 1.36
Required by use of MaybeUninit in the thread_local crate.

    error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
      --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/thread_local-1.1.1/src/lib.rs:81:5
       |
    81 | use std::mem::MaybeUninit;
       |     ^^^^^^^^^^^^^^^^^^^^^