Raise minimum tested compiler to rustc 1.37
Required by the use of `const _` in memchr, which is a transitive
dependency of assert_cmd.

error[E0658]: naming constants with `_` is unstable
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.0/src/memmem/prefilter/fallback.rs:37:1
   |
37 | const _: PrefilterFnTy = find;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^