Raise minimum toolchain to rust 1.62
Required by inventory 0.3.

    error: package `inventory v0.3.3` cannot be built because it
    requires rustc 1.62 or newer, while the currently active rustc
    version is 1.61.0