Raise minimum tested compiler to rustc 1.40
Required by #[non_exhaustive] in memchr.

    error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
       --> .cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.0/src/memmem/prefilter/mod.rs:152:1
        |
    152 | #[non_exhaustive]
        | ^^^^^^^^^^^^^^^^^